//
// Created by emmet on 19/10/2024.
//

#ifndef LAB01_EMBDEDDEDSYSTEMSENGINEERING_TREE_H
#define LAB01_EMBDEDDEDSYSTEMSENGINEERING_TREE_H

int tree_main();

#endif //LAB01_EMBDEDDEDSYSTEMSENGINEERING_TREE_H
